Models/EmprestimoModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Emprestimo_de_livro.Models
{
    public class EmprestimoModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Digite o nome do Recebedor")]
        public string Recebedor { get; set; }
        [Required(ErrorMessage = "Digite o nome do Fornecedor")]
        public string Fornecedor { get; set; }
        [Required(ErrorMessage = "Digite o nome do Livro")]
        public string LivroEmprestado { get; set;}
        public DateTime dataUltimaAtualizacao { get; set; } = DateTime.Now;

        
    }
}

Models/ErrorViewModel.cs
namespace Emprestimo_de_livro.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/EmprestimoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Emprestimo_de_livro.Data;
using Emprestimo_de_livro.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Emprestimo_de_livro.Controllers
{
 
    public class EmprestimoController : Controller
    {
       
       readonly private ApplicationDbContext _db;
        public EmprestimoController(ApplicationDbContext db)
        {
           _db = db; 
        }
        public IActionResult Index()
        {
            IEnumerable<EmprestimoModel> emprestimos = _db.Emprestimo;
            return View(emprestimos);
        }

        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(EmprestimoModel emprestimos)
        {
            if (ModelState.IsValid)
            {
                _db.Emprestimo.Add(emprestimos);
                _db.SaveChanges();

                TempData["MensagemSucesso"] = "Cadastro realizado com sucesso";

                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        public IActionResult Editar(int? id )
        {
            if (id == null || id ==0)
            {
                return NotFound();
            }

            EmprestimoModel emprestimo = _db.Emprestimo.FirstOrDefault(x => x.Id == id);
             
              if (id == null)
            {
                return NotFound();
            }

            return View(emprestimo);
        }

        [HttpPost]
        public IActionResult Editar(EmprestimoModel emprestimo)
        {
            if (ModelState.IsValid)
            {
                _db.Emprestimo.Update(emprestimo);
                _db.SaveChanges();

                 TempData["MensagemSucesso"] = "Edição realizado com sucesso";
                return RedirectToAction("Index");
            }

            return View(emprestimo);
        }

        [HttpGet]
        public IActionResult Excluir (int? id )
        {
            if (id == null || id ==0)
            {
                return NotFound();
            }

            EmprestimoModel emprestimo = _db.Emprestimo.FirstOrDefault(x => x.Id == id);
             
              if (id == null)
            {
                return NotFound();
            }

            return View(emprestimo);
        }

        [HttpPost]
        public IActionResult Excluir(EmprestimoModel emprestimo)
        {
            if (emprestimo == null)
            {
                return NotFound();
            }

            _db.Emprestimo.Remove(emprestimo);
            _db.SaveChanges();
            TempData["MensagemSucesso"] = "Item excluido com sucesso";



            return RedirectToAction("Index");
        }

}
} 

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Emprestimo_de_livro.Models;

namespace Emprestimo_de_livro.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Emprestimo/Cadastrar.cshtml
@model EmprestimoModel

@{
    ViewData["title"]="Cadastrar emprestimo";
}

<div class="container bg-dark p-5 rounded-5">

 <div class="mb-5 text-center">
    <h1 class="text-light">Cadastro de emprestimo</h1>
</div>

<form method="post" asp-controller="Emprestimo" asp-action="Cadastrar">
  <div class="mb-3">
    <label for="Recebedor" class="form-label text-light">Recebedor:</label>
    <input type="text" class="form-control text-light" asp-for="Recebedor" id="Recebedor" placeholder="Quem esta recebendo o livro?">
    <spam class = "text-danger" asp-validation-for="Recebedor"></spam>
  </div>

  <div class="mb-3">
    <label for="Fornecedor" class="form-label text-light">Fornecedor</label>
    <input type="text" class="form-control text-light" asp-for="Fornecedor" id="Fornecedor" placeholder="Quem esta emprestando o livro?">
    <spam class = "text-danger" asp-validation-for="Fornecedor"></spam>
  </div>

  <div class="mb-3">
    <label for="Livro" class="form-label text-light">Livro</label>
    <input type="text" class="form-control text-light" asp-for="LivroEmprestado" id="Livro" placeholder="Qual livro esta sendo emprestado ">
    <spam  class = "text-danger" asp-validation-for="LivroEmprestado"></spam>
  </div>

  <div class="d-flex gap-5 mt-5">
  <button type="submit" class="btn btn-success w-50">Cadastrar</button>
  <a button type="button" class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
  </div>
</form>
</div>

Views/Emprestimo/Editar.cshtml
@model EmprestimoModel

@{
    ViewData["title"]="Editar emprestimo";
}

<div class="container bg-dark p-5 rounded-5">

 <div class="mb-5 text-center">
    <h1 class="text-light">Editar emprestimo</h1>
</div>

<form method="post" asp-controller="Emprestimo" asp-action="Editar">
    <input type="hidden" asp-for="Id"/>
  <div class="mb-3">
    <label for="Recebedor" class="form-label text-light">Recebedor:</label>
    <input type="text" class="form-control text-light" asp-for="Recebedor" id="Recebedor" placeholder="Quem esta recebendo o livro?">
    <spam class ="text-danger" asp-validation-for="Recebedor"></spam>
  </div>

  <div class="mb-3">
    <label for="Fornecedor" class="form-label text-light">Fornecedor</label>
    <input type="text" class="form-control text-light" asp-for="Fornecedor" id="Fornecedor" placeholder="Quem esta emprestando o livro?">
    <spam class ="text-danger" asp-validation-for="Fornecedor"></spam>
  </div>

  <div class="mb-3">
    <label for="Livro" class="form-label text-light">Livro</label>
    <input type="text" class="form-control text-light" asp-for="LivroEmprestado" id="Livro" placeholder="Qual livro esta sendo emprestado ">
    <spam  class ="text-danger" asp-validation-for="LivroEmprestado" ></spam>
  </div>

  <div class="d-flex gap-5 mt-5">
  <button type="submit" class="btn btn-success w-50">Editar</button>
  <a button type="button" class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
  </div>
</form>
</div>

Views/Emprestimo/Excluir.cshtml
@model EmprestimoModel

@{
    ViewData["title"]="Excluir emprestimo";
}

<div class="container bg-dark p-5 rounded-5">

 <div class="mb-5 text-center">
    <h1 class="text-light">Excluir emprestimo</h1>
</div>

<form method="post" asp-controller="Emprestimo" asp-action="Excluir">
    <input type="hidden" asp-for="Id" />
    <div class="mb-5 text-center">
    <h2 class="text-light">Tem certeza que deseja excluir?</h2>
    </div>
  <div class="mb-3">
    <label for="Recebedor" class="form-label text-light">Recebedor:</label>
    <input type="text" class="form-control text-light" asp-for="Recebedor" id="Recebedor" placeholder="Quem esta recebendo o livro?" disabled>
    <spam class = "text-danger" asp-validation-for="Recebedor"></spam>
  </div>

  <div class="mb-3">
    <label for="Fornecedor" class="form-label text-light">Fornecedor</label>
    <input type="text" class="form-control text-light" asp-for="Fornecedor" id="Fornecedor" placeholder="Quem esta emprestando o livro?" disabled>
    <spam class = "text-danger" asp-validation-for="Fornecedor"></spam>
  </div>

  <div class="mb-3">
    <label for="Livro" class="form-label text-light">Livro</label>
    <input type="text" class="form-control text-light" asp-for="LivroEmprestado" id="Livro" placeholder="Qual livro esta sendo emprestado" disabled>
    <spam  class = "text-danger" asp-validation-for="LivroEmprestado"></spam>
  </div>

  <div class="d-flex gap-5 mt-5">
  <button type="submit" class="btn btn-danger w-50">Excluir</button>
  <a button type="button" class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
  </div>
</form>
</div>

Views/Emprestimo/Index.cshtml
@model IEnumerable<EmprestimoModel>

<div class="container">

  <div class="d-flex justify-content-between align-items-center mb-5">
    <h1>Emprestimos</h1>
    <a button type="button" class="btn btn-success" asp-controller="Emprestimo" asp-action="Cadastrar"><i class="bi bi-file-plus mx-2"></i>Cadastrar novo emprestimo</a>
  </div>

  @if(TempData["MensagemSucesso"] != null)
  {
    <div class="alert alert-sucess text-light" role="alert">
      @TempData["MensagemSucesso"]
    </div>
  }

<table id="Emprestimos" class="table table-light table-hover mt-5">
  <thead>
    <tr>
      <th scope="col">Recebedor</th>
      <th scope="col">Fornecedor</th>
      <th scope="col">Livro</th>
      <th scope="col">Ultima atualização</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    @if (Model != null)
    {
        @foreach (var emprestimo in Model)
        {
    <tr>
      <th scope="row">@emprestimo.Recebedor</th>
      <td>@emprestimo.Fornecedor</td>
      <td>@emprestimo.LivroEmprestado</td>
      <td>@emprestimo.dataUltimaAtualizacao</td>
      <td>
        <a asp-controller="Emprestimo" asp-action="Editar" asp-route-id="@emprestimo.Id" class="btn btn-warning mx-2"><i class="bi bi-pencil mx-2"></i>Editar</a>
        <a asp-controller="Emprestimo" asp-action="Excluir" asp-route-id="@emprestimo.Id" class="btn btn-danger mx-2"><i class="bi bi-trash mx-2"></i>Excluir</a>
      </td>
    </tr>
    
        }
    }
  </tbody>
</table>

</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}
<div class="text-center">
   <h1 class="display-4">Emprestimo</h1>
   <p>Vá ler e devolva o livro!!!</p>
   <div>
    <img src="/img/cartoon-characters-png-44249.png" width="520" height="405"/>
   </div>


</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Emprestimo de livro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Material.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Emprestimo_de_livro.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.5/datatables.min.css" rel="stylesheet"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">Emprestimo de livro</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-house-fill mx-2"></i>Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Emprestimo" asp-action="Index"><i class="bi bi-book mx-2"></i>Emprestimos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-dark">
        <div class="container text-dark">
            &copy; 2023 - Emprestimo de livro - 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.5/datatables.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>